fragment PageParts on Page {
  __typename
  title
  description
  heroImage
  body
}

fragment InsightParts on Insight {
  __typename
  title
  coverImage
  excerpt
  body
  author
  authorPosition
  authorImage
  publishedDate
  updatedDate
  category
}

fragment ServiceParts on Service {
  __typename
  title
  description
  image
  icon
  features
  body
  order
}

fragment TeamMemberParts on TeamMember {
  __typename
  name
  position
  specialty
  photo
  bio
  email
  order
}

fragment EventParts on Event {
  __typename
  title
  date
  endDate
  time
  location
  image
  description
  category
  featured
  body
  registrationUrl
}
