//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  insight: Insight;
  insightConnection: InsightConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  teamMember: TeamMember;
  teamMemberConnection: TeamMemberConnection;
  event: Event;
  eventConnection: EventConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryInsightArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryInsightConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InsightFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryTeamMemberArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamMemberConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamMemberFilter>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  insight?: InputMaybe<InsightFilter>;
  service?: InputMaybe<ServiceFilter>;
  teamMember?: InputMaybe<TeamMemberFilter>;
  event?: InputMaybe<EventFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Insight | Service | TeamMember | Event | Folder;

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Insight = Node & Document & {
  __typename?: 'Insight';
  title: Scalars['String']['output'];
  coverImage: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  author: Scalars['String']['output'];
  authorPosition?: Maybe<Scalars['String']['output']>;
  authorImage?: Maybe<Scalars['String']['output']>;
  publishedDate: Scalars['String']['output'];
  updatedDate?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type InsightFilter = {
  title?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  excerpt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  author?: InputMaybe<StringFilter>;
  authorPosition?: InputMaybe<StringFilter>;
  authorImage?: InputMaybe<ImageFilter>;
  publishedDate?: InputMaybe<DatetimeFilter>;
  updatedDate?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
};

export type InsightConnectionEdges = {
  __typename?: 'InsightConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Insight>;
};

export type InsightConnection = Connection & {
  __typename?: 'InsightConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<InsightConnectionEdges>>>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ServiceFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  icon?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type TeamMember = Node & Document & {
  __typename?: 'TeamMember';
  name: Scalars['String']['output'];
  position: Scalars['String']['output'];
  specialty?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['JSON']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamMemberFilter = {
  name?: InputMaybe<StringFilter>;
  position?: InputMaybe<StringFilter>;
  specialty?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<RichTextFilter>;
  email?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TeamMemberConnectionEdges = {
  __typename?: 'TeamMemberConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TeamMember>;
};

export type TeamMemberConnection = Connection & {
  __typename?: 'TeamMemberConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamMemberConnectionEdges>>>;
};

export type Event = Node & Document & {
  __typename?: 'Event';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  endDate?: Maybe<Scalars['String']['output']>;
  time?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  registrationUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  endDate?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
  registrationUrl?: InputMaybe<StringFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateInsight: Insight;
  createInsight: Insight;
  updateService: Service;
  createService: Service;
  updateTeamMember: TeamMember;
  createTeamMember: TeamMember;
  updateEvent: Event;
  createEvent: Event;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateInsightArgs = {
  relativePath: Scalars['String']['input'];
  params: InsightMutation;
};


export type MutationCreateInsightArgs = {
  relativePath: Scalars['String']['input'];
  params: InsightMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateTeamMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMemberMutation;
};


export type MutationCreateTeamMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMemberMutation;
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  insight?: InputMaybe<InsightMutation>;
  service?: InputMaybe<ServiceMutation>;
  teamMember?: InputMaybe<TeamMemberMutation>;
  event?: InputMaybe<EventMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  insight?: InputMaybe<InsightMutation>;
  service?: InputMaybe<ServiceMutation>;
  teamMember?: InputMaybe<TeamMemberMutation>;
  event?: InputMaybe<EventMutation>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type InsightMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  authorPosition?: InputMaybe<Scalars['String']['input']>;
  authorImage?: InputMaybe<Scalars['String']['input']>;
  publishedDate?: InputMaybe<Scalars['String']['input']>;
  updatedDate?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TeamMemberMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  position?: InputMaybe<Scalars['String']['input']>;
  specialty?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['JSON']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type EventMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  registrationUrl?: InputMaybe<Scalars['String']['input']>;
};

export type PagePartsFragment = { __typename: 'Page', title: string, description?: string | null, heroImage?: string | null, body?: any | null };

export type InsightPartsFragment = { __typename: 'Insight', title: string, coverImage: string, excerpt?: string | null, body?: any | null, author: string, authorPosition?: string | null, authorImage?: string | null, publishedDate: string, updatedDate?: string | null, category?: string | null };

export type ServicePartsFragment = { __typename: 'Service', title: string, description?: string | null, image?: string | null, icon?: string | null, features?: Array<string | null> | null, body?: any | null, order?: number | null };

export type TeamMemberPartsFragment = { __typename: 'TeamMember', name: string, position: string, specialty?: string | null, photo?: string | null, bio?: any | null, email?: string | null, order?: number | null };

export type EventPartsFragment = { __typename: 'Event', title: string, date: string, endDate?: string | null, time?: string | null, location?: string | null, image?: string | null, description?: string | null, category?: string | null, featured?: boolean | null, body?: any | null, registrationUrl?: string | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, description?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, description?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type InsightQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type InsightQuery = { __typename?: 'Query', insight: { __typename: 'Insight', id: string, title: string, coverImage: string, excerpt?: string | null, body?: any | null, author: string, authorPosition?: string | null, authorImage?: string | null, publishedDate: string, updatedDate?: string | null, category?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type InsightConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InsightFilter>;
}>;


export type InsightConnectionQuery = { __typename?: 'Query', insightConnection: { __typename?: 'InsightConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'InsightConnectionEdges', cursor: string, node?: { __typename: 'Insight', id: string, title: string, coverImage: string, excerpt?: string | null, body?: any | null, author: string, authorPosition?: string | null, authorImage?: string | null, publishedDate: string, updatedDate?: string | null, category?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, title: string, description?: string | null, image?: string | null, icon?: string | null, features?: Array<string | null> | null, body?: any | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, title: string, description?: string | null, image?: string | null, icon?: string | null, features?: Array<string | null> | null, body?: any | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TeamMemberQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamMemberQuery = { __typename?: 'Query', teamMember: { __typename: 'TeamMember', id: string, name: string, position: string, specialty?: string | null, photo?: string | null, bio?: any | null, email?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamMemberConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamMemberFilter>;
}>;


export type TeamMemberConnectionQuery = { __typename?: 'Query', teamMemberConnection: { __typename?: 'TeamMemberConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamMemberConnectionEdges', cursor: string, node?: { __typename: 'TeamMember', id: string, name: string, position: string, specialty?: string | null, photo?: string | null, bio?: any | null, email?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EventQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventQuery = { __typename?: 'Query', event: { __typename: 'Event', id: string, title: string, date: string, endDate?: string | null, time?: string | null, location?: string | null, image?: string | null, description?: string | null, category?: string | null, featured?: boolean | null, body?: any | null, registrationUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
}>;


export type EventConnectionQuery = { __typename?: 'Query', eventConnection: { __typename?: 'EventConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventConnectionEdges', cursor: string, node?: { __typename: 'Event', id: string, title: string, date: string, endDate?: string | null, time?: string | null, location?: string | null, image?: string | null, description?: string | null, category?: string | null, featured?: boolean | null, body?: any | null, registrationUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  description
  heroImage
  body
}
    `;
export const InsightPartsFragmentDoc = gql`
    fragment InsightParts on Insight {
  __typename
  title
  coverImage
  excerpt
  body
  author
  authorPosition
  authorImage
  publishedDate
  updatedDate
  category
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  title
  description
  image
  icon
  features
  body
  order
}
    `;
export const TeamMemberPartsFragmentDoc = gql`
    fragment TeamMemberParts on TeamMember {
  __typename
  name
  position
  specialty
  photo
  bio
  email
  order
}
    `;
export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  title
  date
  endDate
  time
  location
  image
  description
  category
  featured
  body
  registrationUrl
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const InsightDocument = gql`
    query insight($relativePath: String!) {
  insight(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...InsightParts
  }
}
    ${InsightPartsFragmentDoc}`;
export const InsightConnectionDocument = gql`
    query insightConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: InsightFilter) {
  insightConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...InsightParts
      }
    }
  }
}
    ${InsightPartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const TeamMemberDocument = gql`
    query teamMember($relativePath: String!) {
  teamMember(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamMemberParts
  }
}
    ${TeamMemberPartsFragmentDoc}`;
export const TeamMemberConnectionDocument = gql`
    query teamMemberConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamMemberFilter) {
  teamMemberConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamMemberParts
      }
    }
  }
}
    ${TeamMemberPartsFragmentDoc}`;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    insight(variables: InsightQueryVariables, options?: C): Promise<{data: InsightQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InsightQueryVariables, query: string}> {
        return requester<{data: InsightQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InsightQueryVariables, query: string}, InsightQueryVariables>(InsightDocument, variables, options);
      },
    insightConnection(variables?: InsightConnectionQueryVariables, options?: C): Promise<{data: InsightConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InsightConnectionQueryVariables, query: string}> {
        return requester<{data: InsightConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InsightConnectionQueryVariables, query: string}, InsightConnectionQueryVariables>(InsightConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    teamMember(variables: TeamMemberQueryVariables, options?: C): Promise<{data: TeamMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberQueryVariables, query: string}> {
        return requester<{data: TeamMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberQueryVariables, query: string}, TeamMemberQueryVariables>(TeamMemberDocument, variables, options);
      },
    teamMemberConnection(variables?: TeamMemberConnectionQueryVariables, options?: C): Promise<{data: TeamMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberConnectionQueryVariables, query: string}> {
        return requester<{data: TeamMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberConnectionQueryVariables, query: string}, TeamMemberConnectionQueryVariables>(TeamMemberConnectionDocument, variables, options);
      },
    event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  